mixed-port: 7890 #监听代理开放端口
allow-lan: true
bind-address: '*' #外部访问开放所有地址
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090 #外部控制地址

http:
  # 强制使用 Stash Engine 以 HTTP 协议处理 TCP 连接
  # 捕获后的连接可以使用高级功能，例如重写和脚本
  mitm:
    - g.cn
    - "*.google.cn"
    - api.m.jd.com
  rewrite:
    - ^https?:\/\/(www.)?(g|google)\.cn https://www.google.com 302
  script:
    - match: ^https?://api\.m\.jd\.com/client\.action\?functionId=(wareBusiness|serverConfig|basicConfig)
      name: jd_historical_price
      type: response
      require-body: true
      timeout: 10

script-providers:
  jd_historical_price:
    url: https://raw.githubusercontent.com/yichahucha/surge/master/jd_price.js
    interval: 86400
    
script:
  shortcuts: # 使用 Python 脚本编写自定义规则
    quic: network == 'udp' and (dst_port == 443) # 可以在 rule 中引用

hosts:
  'localhost': 127.0.0.1
  '360.com': 127.0.0.1

dns:
  # default dns 服务器，用来解析下面 nameserver 定义的 dns 服务器地址
  # 仅填写 DNS 服务器的 IP 地址
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  # 解析域名使用的 dns 服务器，此处的 dns 地址会通过上面的 default dns 服务器解析
  nameserver:
    # 不建议配置超过 2 个 DNS 服务器，会增加系统功耗
    - 223.5.5.5
    - 114.114.114.114
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query

  # 对部分域名使用单独的 DNS 服务器
  nameserver-policy:
    "www.taobao.com": 223.5.5.5

  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  # 在以下列表的域名将不会被解析为 fake ip，这些域名相关的解析请求将会返回它们真实的 IP 地址
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.localhost"
    - "*.local"

proxy-providers:
  out-proxy-1:
    url:
    interval: 3600
    filter: 'out-proxy-1'
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  out-proxy-2:
    url:
    interval: 3600
    filter: 'out-proxy-2'
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

proxy-groups:
  # url-test 可以自动选择与指定 URL 测速后，延迟最短的服务器
  - name: "auto"
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Auto.png
    use:
      - out-proxy-1  # proxy-providers 里的节点需要用 use 调用
      - out-proxy-2
    url: "http://www.gstatic.com/generate_204"
    interval: 300

  # select 用来允许用户手动选择 代理服务器 或 服务器组
  # 您也可以使用 RESTful API 去切换服务器，这种方式推荐在 GUI 中使用
  - name: PROXY
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png
    use:
      - out-proxy-1
      - out-proxy-2
    proxies:
      - auto  # 当前 config 里定义的节点或组需要用 proxies 调用

  # 基于 SSID 的策略，方便在特殊网络环境下使用特定的代理
  - name: ssid-group
    type: select # 类型必须为 select，兼容原版 clash 配置
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/SSID.png
    use:
      - out-proxy-1
      - out-proxy-2
    proxies:
      - PROXY
      - auto
      - DIRECT
    ssid-policy:
      # 在 SSID 为 ssid-1 的 Wi-Fi 中自动切换为 auto 策略
      # 其他的 SSID 以及蜂窝数据，默认为 DIRECT
      ssid-1: PROXY
      default: DIRECT

rule-providers:
  Lan:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml"
    interval: 86400

  Advertising:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.yaml"
    interval: 86400

  Advertising_Domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Domain.yaml"
    interval: 86400

  ChinaMax:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax.yaml"
    interval: 86400

  ChinaMax_Domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Domain.yaml"
    interval: 86400

  ChinaMax_IP:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_IP.yaml"
    interval: 86400

rules:
  # PROXY added
  - DOMAIN-SUFFIX,raw.githubusercontent.com,PROXY
  - DOMAIN-SUFFIX,ap-oversea-tls.agora.io,PROXY
  - DOMAIN-SUFFIX,testflight.apple.com,PROXY
  - DOMAIN-SUFFIX,recaptcha.net,PROXY
  # direct added
  - DOMAIN-SUFFIX,email.advertising.newtimeai.com,DIRECT
  - DOMAIN-SUFFIX,wxs.qq.com,DIRECT
  - DOMAIN-SUFFIX,amdc.m.taobao.com,DIRECT
  - DOMAIN-SUFFIX,rerevod.info,DIRECT
  - DOMAIN-SUFFIX,rerevod.net,DIRECT
  - DOMAIN-SUFFIX,hdchina.org,DIRECT
  - DOMAIN-SUFFIX,alipayobjects.com,DIRECT
  - DOMAIN-SUFFIX,alicdn.com,DIRECT
  - DOMAIN-SUFFIX,speedtest.net,DIRECT
  - DOMAIN-SUFFIX,163.com,DIRECT
  - DOMAIN-SUFFIX,zdmimg.com,DIRECT
  - DOMAIN-SUFFIX,smzdm.com,DIRECT
  - DOMAIN-SUFFIX,umeng.com,DIRECT
  - DOMAIN-SUFFIX,10010.com,DIRECT
  - DOMAIN-SUFFIX,360buyimg.com,DIRECT
  - DOMAIN-SUFFIX,jd.com,DIRECT
  - DOMAIN-SUFFIX,app-measurement.com,DIRECT
  - DOMAIN-SUFFIX,niekun.net,DIRECT
  # direct apple
  - DOMAIN-SUFFIX,apple.com,DIRECT
  - DOMAIN-SUFFIX,apple.cn,DIRECT
  - DOMAIN-SUFFIX,mail.me.com,DIRECT
  - DOMAIN-SUFFIX,mail.me.com.akadns.net,DIRECT
  - DOMAIN-SUFFIX,icloud.com,DIRECT
  - DOMAIN-SUFFIX,icloud.com.cn,DIRECT
  - DOMAIN-SUFFIX,itunes.com,DIRECT
  - DOMAIN-SUFFIX,mzstatic.com,DIRECT
  - DOMAIN-SUFFIX,icloud-content.com,DIRECT
  - DOMAIN-SUFFIX,updates-http.cdn-apple.com,DIRECT
  - DOMAIN-SUFFIX,updates.cdn-apple.com,DIRECT
  - DOMAIN-SUFFIX,iosapps.itunes.apple.com,DIRECT
  # DIRECT baidu
  - DOMAIN-SUFFIX,wappass.baidu.com,DIRECT
  - DOMAIN-SUFFIX,passport.baidu.com,DIRECT
  - DOMAIN-SUFFIX,yun.baidu.com,DIRECT
  - DOMAIN-SUFFIX,pan.baidu.com,DIRECT
  - DOMAIN-SUFFIX,wenku.baidu.com,DIRECT
  - DOMAIN-SUFFIX,zhidao.baidu.com,DIRECT
  - DOMAIN-SUFFIX,baike.baidu.com,DIRECT

  - SCRIPT,quic,REJECT
  - RULE-SET,Advertising,REJECT
  - RULE-SET,Advertising_Domain,REJECT

  - RULE-SET,Lan,DIRECT
  - RULE-SET,ChinaMax,DIRECT
  - RULE-SET,ChinaMax_Domain,DIRECT
  - RULE-SET,ChinaMax_IP,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
