#!/bin/bash /etc/rc.common

USE_PROCD=1
START=99
STOP=15

TRANS_SCRIPT="/etc/v2ray/script/transparent.sh"
TRANS_CLEAN_SCRIPT="/etc/v2ray/script/transparent-clean.sh"
CLEAN_SCRIPT="/etc/v2ray/script/autoremove_log.sh"

start_service() {
        procd_open_instance
        procd_set_param command /bin/bash "$TRANS_SCRIPT" ; /bin/sh "$CLEAN_SCRIPT"
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}

stop_service() {
        /bin/bash "$TRANS_CLEAN_SCRIPT"
}

restart_service() {
        stop
        start
}
