#!name=marco-common
#!desc=personal use common rules

[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 27.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
tun-excluded-routes = %APPEND% 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32
fallback-dns-server = system
ipv6 = false
prefer-ipv6 = false
dns-direct-system = false
icmp-auto-reply = true
always-reject-url-rewrite = false
private-ip-answer = true
# direct domain fail to resolve use proxy rule
dns-direct-fallback-proxy = true
# The fallback behavior when UDP traffic matches a policy that doesn't support the UDP relay. Possible values: DIRECT, REJECT.
udp-policy-not-supported-behaviour = REJECT

[Rule]
# Block HTTP3/QUIC
AND,((PROTOCOL,UDP),(DEST-PORT,443)),REJECT-NO-DROP
# REJECT added
DOMAIN-SUFFIX,360.com,REJECT
DOMAIN-SUFFIX,360.cn,REJECT

# direct IP-CIDR
IP-CIDR,104.224.160.217/32,DIRECT
IP-CIDR,27.168.0.0/16,DIRECT
IP-CIDR,10.168.0.0/16,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Lan/Lan.list,DIRECT

[Host]
localhost = 127.0.0.1
taobao.com = server:223.5.5.5

[MITM]
enable = true
