[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 27.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
tun-excluded-routes = %APPEND% 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32
ipv6 = false
prefer-ipv6 = false
dns-fallback-system = false
dns-direct-system = false
icmp-auto-reply = true
always-reject-url-rewrite = false
private-ip-answer = true
dns-direct-fallback-proxy = true

[Rule]
# REJECT added
DOMAIN-SUFFIX,360.com,REJECT
DOMAIN-SUFFIX,360.cn,REJECT

# direct IP-CIDR
IP-CIDR,104.224.160.217/32,DIRECT
IP-CIDR,27.168.0.0/16,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Lan/Lan.list,DIRECT

[Host]
localhost = 127.0.0.1

[MITM]
enable = true
