#!name=Spotify(iOS15)
#!desc=部分解锁premium,建议重新登录,音质不能设置为超高

[Script]
spotify-proto = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-proto.js,max-size=1048576,requires-body=true,timeout=60,script-update-interval=90000,enable=true

[MITM]
hostname = %APPEND% spclient.wg.spotify.com
