[Script]
unblockWechatUrlLimit = type=http-response,script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/asset/UnblockURLinWeChat.js,pattern=^https\:\/\/(weixin110\.qq|security.wechat)\.com\/cgi-bin\/mmspamsupport-bin\/newredirectconfirmcgi\?,max-size=1048576,requires-body=true,timeout=60,script-update-interval=90000,enable=true

[MITM]
hostname = %APPEND% security.wechat.com, weixin110.qq.com
