[URL Rewrite]
^https?:\/\/.+\.googlevideo\.com\/.+&oad _ reject-img
^https?:\/\/.+\.googlevideo\.com\/.+ctier _ reject-img
^https?:\/\/youtubei\.googleapis\.com\/youtubei\/.+ad_ _ reject-img
^https?:\/\/youtubei\.googleapis\.com\/youtubei\/.+log_ _ reject-img
^https?:\/\/.+\.youtube\.com\/get_midroll_ _ reject-img
^https?:\/\/premiumyva\.appspot\.com\/vmclickstoadvertisersite _ reject-img
^https?:\/\/.+\.youtube\.com\/api\/stats\/ads _ reject-img
^https?:\/\/.+\.youtube\.com\/api\/stats\/.+adformat _ reject-img
^https?:\/\/.+\.youtube\.com\/pagead\/ _ reject-img
^https?:\/\/.+\.youtube\.com\/ptracking _ reject-img
