#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=15

start_service() {
        procd_open_instance
        procd_set_param command /bin/sh /etc/v2ray/transparent.sh
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}
stop_service() {
        /bin/sh /etc/v2ray/transparent-clean.sh
}
restart_service() {
        stop
        start
}
