#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90
STOP=15

CONFDIR=/etc/v2ray/conf.d
PROG=/usr/bin/v2ray

start_service() {
        procd_open_instance
        procd_set_param limits core="unlimited"
        procd_set_param limits nofile="101238"
        procd_set_param limits nproc="101238"
        procd_set_param command $PROG -confdir $CONFDIR
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-9}
        procd_close_instance
}
stop_service() {
        kill $(ps | grep v2ray | awk '/-confdir/ {print $1}')
}
restart_service() {
        stop
        start
}
