#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90
STOP=15

CONFIG=/etc/v2ray/conf.d/config.json
PROG=/usr/bin/v2ray

start_service() {
        procd_open_instance
        procd_set_param user v2ray_tproxy # 以 v2ray_tproxy 用户运行服务 需要提前创建此用户
        procd_set_param limits core="unlimited"
        procd_set_param limits nofile="1000000"   # 解决 too many open files 问题 设置此进程的句柄数限制 cat /proc/sys/fs/file-max 返回值查看
        procd_set_param limits nproc="500"        # 解决 too many open files 问题
        procd_set_param command $PROG -config $CONFIG -format jsonv5
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-9}
        procd_close_instance
}
stop_service() {
        kill $(ps | grep v2ray | awk '/-config/ {print $1}')
}
restart_service() {
        stop
        start
}
